name: "Branch build"
on:
  push:
    branches: [develop]
jobs:
  install-notest:
    runs-on: ubuntu-latest
    name: "Package and linting"
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 16
          architecture: x64
      - name: Cache Maven packages
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2
          key: ubuntu-latest-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ubuntu-latest-m2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java
      - name: Test with Maven
        run: mvn install -DskipTests
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
